version: "3.7"

services:
    app:
        build:
            args:
                user: sigma-user
                uid: "${UID}"
            context: ./
            dockerfile: Dockerfile
        image: sigma-pet
        container_name: sigma-pet-api
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - sigma-pet
    nginx:
        image: nginx:1.21.6
        container_name: sigma-pet-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - sigma-pet

networks:
    sigma-pet:
        driver: bridge
